"""Underwriting Exception Memo generator.
Produces professional PDF memos for flagged/rejected applications."""
from jinja2 import Template
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

MEMO_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        @page { size: letter; margin: 1in; }
        body { font-family: 'Helvetica Neue', Arial, sans-serif; font-size: 11pt; line-height: 1.5; color: #1a1a1a; }
        .header { border-bottom: 3px solid #1e3a5f; padding-bottom: 15px; margin-bottom: 25px; }
        .header h1 { color: #1e3a5f; font-size: 20pt; margin: 0; }
        .header .sub { color: #666; font-size: 10pt; margin-top: 5px; }
        .badge { display: inline-block; padding: 4px 12px; border-radius: 4px; font-weight: bold; font-size: 10pt; }
        .badge-critical { background: #fee2e2; color: #991b1b; }
        .badge-warning { background: #fef3c7; color: #92400e; }
        .badge-info { background: #dbeafe; color: #1e40af; }
        .section { margin: 20px 0; }
        .section h2 { color: #1e3a5f; font-size: 13pt; border-left: 4px solid #1e3a5f; padding-left: 10px; }
        table { width: 100%; border-collapse: collapse; margin: 10px 0; font-size: 10pt; }
        th, td { padding: 8px 10px; text-align: left; border-bottom: 1px solid #e5e7eb; }
        th { background: #f8fafc; font-weight: 600; color: #374151; }
        .metric-box { background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 6px; padding: 15px; margin: 10px 0; }
        .metric-row { display: flex; justify-content: space-between; margin: 5px 0; }
        .metric-label { color: #6b7280; }
        .metric-value { font-weight: 600; }
        .footer { margin-top: 40px; padding-top: 15px; border-top: 1px solid #e5e7eb; font-size: 9pt; color: #9ca3af; }
        .violation-row { padding: 10px; margin: 8px 0; border-radius: 4px; }
        .violation-critical { background: #fef2f2; border-left: 4px solid #dc2626; }
        .violation-warning { background: #fffbeb; border-left: 4px solid #f59e0b; }
        .violation-info { background: #eff6ff; border-left: 4px solid #3b82f6; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Underwriting Exception Memo</h1>
        <div class="sub">
            Application ID: {{ application_id }} | Date: {{ date }}<br>
            Borrower: {{ borrower_name }} | Generated by PacketWise Automation System
        </div>
    </div>

    <div class="section">
        <h2>Decision Summary</h2>
        <p><strong>Overall Decision:</strong> 
            <span class="badge badge-{{ decision_class }}">{{ decision.upper() }}</span>
        </p>
        <p><strong>Underwriter Action Required:</strong> {{ action_required }}</p>
    </div>

    <div class="section">
        <h2>Financial Metrics</h2>
        <div class="metric-box">
            {% for key, value in metrics.items() %}
            <div class="metric-row">
                <span class="metric-label">{{ key|replace('_', ' ')|title }}:</span>
                <span class="metric-value">
                    {% if value is none %}N/A
                    {% elif 'ratio' in key %}{{ "%.2f"|format(value*100) }}%
                    {% elif 'income' in key or 'debt' in key or 'balance' in key %}${{ "{:,.2f}".format(value) }}
                    {% else %}{{ value }}{% endif %}
                </span>
            </div>
            {% endfor %}
        </div>
    </div>

    <div class="section">
        <h2>Rule Violations ({{ violations|length }} found)</h2>
        {% for v in violations %}
        <div class="violation-row violation-{{ v.severity }}">
            <strong>[{{ v.severity.upper() }}] {{ v.rule_code }}</strong><br>
            {{ v.description }}<br>
            <em>Expected:</em> {{ v.expected_value or 'N/A' }} | 
            <em>Actual:</em> {{ v.actual_value or 'N/A' }}
        </div>
        {% endfor %}
    </div>

    <div class="section">
        <h2>Document Inventory</h2>
        <table>
            <tr><th>Document Type</th><th>Extraction Confidence</th><th>Status</th></tr>
            {% for doc in documents %}
            <tr>
                <td>{{ doc.type|replace('_', ' ')|title }}</td>
                <td>{{ "%.1f"|format(doc.confidence*100) }}%</td>
                <td>{% if doc.errors %}⚠️ Errors{% else %}✅ Clean{% endif %}</td>
            </tr>
            {% endfor %}
        </table>
    </div>

    <div class="section">
        <h2>Underwriter Notes</h2>
        <p style="border: 1px solid #e5e7eb; padding: 15px; min-height: 60px; background: #fafafa;">
            _________________________________________________<br><br>
            _________________________________________________<br><br>
            _________________________________________________
        </p>
    </div>

    <div class="footer">
        PacketWise v1.0 | Automated Underwriting System | Confidential — For Internal Use Only<br>
        Generated: {{ timestamp }} | Processing Time: {{ processing_time }}s | Extraction Confidence: {{ confidence }}%
    </div>
</body>
</html>
"""

class MemoGenerator:
    """Generates professional underwriting exception memos."""

    def __init__(self, output_dir: str = "data/exceptions"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.template = Template(MEMO_TEMPLATE)

    def generate(self, application_id: str, borrower_name: str,
                 decision: str, metrics: Dict[str, Any],
                 violations: List[Dict[str, Any]],
                 documents: List[Dict[str, Any]],
                 processing_time: float = 0,
                 confidence: float = 0) -> str:
        """Generate PDF memo and return file path."""

        decision_class = "critical" if decision == "rejected" else ("warning" if decision == "flagged" else "info")
        action_required = {
            "rejected": "Application does not meet minimum underwriting criteria. Review for potential manual override.",
            "flagged": "Application requires manual underwriter review due to policy exceptions.",
            "approved": "No exceptions noted. File is clear for approval.",
            "manual_review": "Application routed to senior underwriter for manual evaluation."
        }.get(decision, "Review required.")

        html = self.template.render(
            application_id=application_id,
            borrower_name=borrower_name,
            date=datetime.now().strftime("%B %d, %Y"),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S UTC"),
            decision=decision,
            decision_class=decision_class,
            action_required=action_required,
            metrics=metrics,
            violations=violations,
            documents=documents,
            processing_time=round(processing_time, 2),
            confidence=round(confidence * 100, 1)
        )

        output_path = self.output_dir / f"exception_memo_{application_id}.pdf"
        try:
            from weasyprint import HTML
            HTML(string=html).write_pdf(str(output_path))
        except Exception:
            # Fallback: save rendered HTML if WeasyPrint/GTK is unavailable
            html_path = self.output_dir / f"exception_memo_{application_id}.html"
            html_path.write_text(html, encoding="utf-8")
            return str(html_path)
        return str(output_path)
