"""Underwriting Exception Memo generator.

Produces professional PDF memos for flagged/rejected applications using
ReportLab's platypus layer. ReportLab replaced WeasyPrint in Sprint 14:
WeasyPrint needs GTK/Pango/Cairo native libraries that are not present on
Windows hosts, so every memo silently fell back to HTML and logged an
import error. See docs/adr/ADR-003-reportlab-over-weasyprint.md.
"""
from pathlib import Path
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib import colors
from reportlab.lib.enums import TA_LEFT
from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, KeepTogether,
)

NAVY = colors.HexColor("#1e3a5f")
INK = colors.HexColor("#1a1a1a")
MUTED = colors.HexColor("#6b7280")
RULE = colors.HexColor("#e5e7eb")
SURFACE = colors.HexColor("#f8fafc")

SEVERITY_COLOURS = {
    "critical": colors.HexColor("#d03b3b"),
    "warning": colors.HexColor("#fab219"),
    "info": colors.HexColor("#2a78d6"),
}

ACTION_REQUIRED = {
    "rejected": "Application does not meet minimum underwriting criteria. "
                "Review for potential manual override.",
    "flagged": "Application requires manual underwriter review due to policy exceptions.",
    "approved": "No exceptions noted. File is clear for approval.",
    "manual_review": "Application routed to senior underwriter for manual evaluation.",
}


ACRONYMS = {"dti": "DTI", "ltv": "LTV", "ssn": "SSN", "agi": "AGI", "w2": "W-2"}


def _fmt_label(key: str) -> str:
    """Title-case a metric key without mangling acronyms ('Dti' -> 'DTI')."""
    return " ".join(ACRONYMS.get(w.lower(), w.capitalize())
                    for w in key.split("_"))


def _fmt_metric(key: str, value: Any) -> str:
    """Format a metric the way the old HTML template did."""
    if value is None:
        return "N/A"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        if "ratio" in key or "variance" in key:
            return f"{value * 100:.2f}%"
        if any(t in key for t in ("income", "debt", "balance", "amount", "value")):
            return f"${value:,.2f}"
        return f"{value:,}" if isinstance(value, int) else f"{value:,.2f}"
    return str(value)


class MemoGenerator:
    """Generates professional underwriting exception memos as PDFs."""

    def __init__(self, output_dir: str = "data/exceptions"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)
        self.styles = self._build_styles()

    # ── styles ──────────────────────────────────────────────────────

    def _build_styles(self):
        base = getSampleStyleSheet()
        s = {
            "title": ParagraphStyle(
                "MemoTitle", parent=base["Title"], fontName="Helvetica-Bold",
                fontSize=19, leading=23, textColor=NAVY, alignment=TA_LEFT,
                spaceAfter=4,
            ),
            "sub": ParagraphStyle(
                "MemoSub", parent=base["Normal"], fontName="Helvetica",
                fontSize=9, leading=13, textColor=MUTED,
            ),
            "h2": ParagraphStyle(
                "MemoH2", parent=base["Heading2"], fontName="Helvetica-Bold",
                fontSize=12, leading=15, textColor=NAVY,
                spaceBefore=16, spaceAfter=6,
            ),
            "body": ParagraphStyle(
                "MemoBody", parent=base["Normal"], fontName="Helvetica",
                fontSize=10, leading=14, textColor=INK,
            ),
            "cell": ParagraphStyle(
                "MemoCell", parent=base["Normal"], fontName="Helvetica",
                fontSize=9, leading=12, textColor=INK,
            ),
            "footer": ParagraphStyle(
                "MemoFooter", parent=base["Normal"], fontName="Helvetica",
                fontSize=8, leading=11, textColor=MUTED,
            ),
        }
        return s

    # ── sections ────────────────────────────────────────────────────

    def _header(self, application_id, borrower_name, date):
        return [
            Paragraph("Underwriting Exception Memo", self.styles["title"]),
            Paragraph(
                f"Application ID: {application_id} &nbsp;|&nbsp; Date: {date}<br/>"
                f"Borrower: {borrower_name} &nbsp;|&nbsp; "
                f"Generated by PacketWise Automation System",
                self.styles["sub"],
            ),
            Spacer(1, 6),
            Table([[""]], colWidths=[6.5 * inch], rowHeights=[2],
                  style=TableStyle([("BACKGROUND", (0, 0), (-1, -1), NAVY)])),
            Spacer(1, 4),
        ]

    def _decision(self, decision: str):
        severity = ("critical" if decision == "rejected"
                    else "warning" if decision == "flagged" else "info")
        chip = Table(
            [[Paragraph(f"<b>{decision.upper()}</b>", self.styles["cell"])]],
            colWidths=[1.3 * inch],
            hAlign="LEFT",
            style=TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
                ("LINEBEFORE", (0, 0), (0, -1), 3, SEVERITY_COLOURS[severity]),
                ("LEFTPADDING", (0, 0), (-1, -1), 8),
                ("TOPPADDING", (0, 0), (-1, -1), 5),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ]),
        )
        return [
            Paragraph("Decision Summary", self.styles["h2"]),
            chip,
            Spacer(1, 6),
            Paragraph(
                f"<b>Underwriter action required:</b> "
                f"{ACTION_REQUIRED.get(decision, 'Review required.')}",
                self.styles["body"],
            ),
        ]

    def _metrics(self, metrics: Dict[str, Any]):
        if not metrics:
            return [Paragraph("Financial Metrics", self.styles["h2"]),
                    Paragraph("No metrics recorded.", self.styles["body"])]

        rows = [[Paragraph(_fmt_label(k), self.styles["cell"]),
                 Paragraph(_fmt_metric(k, v), self.styles["cell"])]
                for k, v in metrics.items()]

        table = Table(rows, colWidths=[3.2 * inch, 3.3 * inch], hAlign="LEFT")
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
            ("BOX", (0, 0), (-1, -1), 0.5, RULE),
            ("INNERGRID", (0, 0), (-1, -1), 0.5, RULE),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return [Paragraph("Financial Metrics", self.styles["h2"]), table]

    def _violations(self, violations: List[Dict[str, Any]]):
        flow = [Paragraph(f"Rule Violations ({len(violations)} found)",
                          self.styles["h2"])]
        if not violations:
            flow.append(Paragraph("None recorded.", self.styles["body"]))
            return flow

        for v in violations:
            severity = (v.get("severity") or "info").lower()
            accent = SEVERITY_COLOURS.get(severity, SEVERITY_COLOURS["info"])
            body = (
                f"<b>[{severity.upper()}] {v.get('rule_code', '')}</b><br/>"
                f"{v.get('description', '')}<br/>"
                f"<i>Expected:</i> {v.get('expected_value') or 'N/A'} &nbsp;|&nbsp; "
                f"<i>Actual:</i> {v.get('actual_value') or 'N/A'}"
            )
            block = Table([[Paragraph(body, self.styles["cell"])]],
                          colWidths=[6.5 * inch], hAlign="LEFT")
            block.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, -1), SURFACE),
                ("LINEBEFORE", (0, 0), (0, -1), 3, accent),
                ("LEFTPADDING", (0, 0), (-1, -1), 9),
                ("RIGHTPADDING", (0, 0), (-1, -1), 9),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
            ]))
            flow.extend([block, Spacer(1, 6)])
        return flow

    def _documents(self, documents: List[Dict[str, Any]]):
        header = ["Document Type", "Extraction Confidence", "Status"]
        rows = [[Paragraph(f"<b>{h}</b>", self.styles["cell"]) for h in header]]
        for doc in documents:
            status = "Errors" if doc.get("errors") else "Clean"
            rows.append([
                Paragraph(str(doc.get("type", "")).replace("_", " ").title(),
                          self.styles["cell"]),
                Paragraph(f"{(doc.get('confidence') or 0) * 100:.1f}%",
                          self.styles["cell"]),
                Paragraph(status, self.styles["cell"]),
            ])

        table = Table(rows, colWidths=[2.8 * inch, 2.0 * inch, 1.7 * inch])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), SURFACE),
            ("LINEBELOW", (0, 0), (-1, 0), 1, RULE),
            ("INNERGRID", (0, 1), (-1, -1), 0.5, RULE),
            ("BOX", (0, 0), (-1, -1), 0.5, RULE),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        return [Paragraph("Document Inventory", self.styles["h2"]), table]

    def _notes(self):
        box = Table([[""]], colWidths=[6.5 * inch], rowHeights=[0.85 * inch])
        box.setStyle(TableStyle([
            ("BOX", (0, 0), (-1, -1), 0.5, RULE),
            ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#fafafa")),
        ]))
        return [Paragraph("Underwriter Notes", self.styles["h2"]), box]

    def _footer(self, canvas_obj, doc):
        canvas_obj.saveState()
        canvas_obj.setStrokeColor(RULE)
        canvas_obj.setLineWidth(0.5)
        canvas_obj.line(inch, 0.85 * inch, letter[0] - inch, 0.85 * inch)
        canvas_obj.setFont("Helvetica", 7.5)
        canvas_obj.setFillColor(MUTED)
        canvas_obj.drawString(inch, 0.70 * inch, doc.memo_footer_left)
        canvas_obj.drawString(inch, 0.58 * inch, doc.memo_footer_right)
        canvas_obj.drawRightString(letter[0] - inch, 0.58 * inch,
                                   f"Page {canvas_obj.getPageNumber()}")
        canvas_obj.restoreState()

    # ── public API ──────────────────────────────────────────────────

    def generate(self, application_id: str, borrower_name: str,
                 decision: str, metrics: Dict[str, Any],
                 violations: List[Dict[str, Any]],
                 documents: List[Dict[str, Any]],
                 processing_time: float = 0,
                 confidence: float = 0) -> str:
        """Generate a PDF memo and return its file path."""
        output_path = self.output_dir / f"exception_memo_{application_id}.pdf"

        doc = SimpleDocTemplate(
            str(output_path),
            pagesize=letter,
            leftMargin=inch, rightMargin=inch,
            topMargin=inch, bottomMargin=inch,
            title=f"Underwriting Exception Memo {application_id}",
            author="PacketWise",
        )
        doc.memo_footer_left = (
            "PacketWise v1.0 | Automated Underwriting System | "
            "Confidential - For Internal Use Only"
        )
        doc.memo_footer_right = (
            f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} | "
            f"Processing Time: {round(processing_time, 2)}s | "
            f"Extraction Confidence: {round(confidence * 100, 1)}%"
        )

        flow = []
        flow += self._header(application_id, borrower_name,
                             datetime.now().strftime("%B %d, %Y"))
        flow += self._decision(decision)
        flow += self._metrics(metrics)
        flow += self._violations(violations)
        flow += self._documents(documents)
        flow += [KeepTogether(self._notes())]

        doc.build(flow, onFirstPage=self._footer, onLaterPages=self._footer)
        return str(output_path)
